(* ::Package:: *)

(************************************************************************)\012(* This file was generated automatically by the Mathematica front end.  *)\012(* It contains Initialization cells from a Notebook file, which         *)\012(* typically will have the same name as this file except ending in      *)\012(* ".nb" instead of ".m".                                               *)\012(*                                                                      *)\012(* This file is intended to be loaded into the Mathematica kernel using *)\012(* the package loading commands Get or Needs.  Doing so is equivalent   *)\012(* to using the Evaluate Initialization Cells menu command in the front *)\012(* end.                                                                 *)\012(*                                                                      *)\012(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)\012(* automatically each time the parent Notebook file is saved in the     *)\012(* Mathematica front end.  Any changes you make to this file will be    *)\012(* overwritten.                                                         *)\012(************************************************************************)\012\012

UnitForm[units_][quantity_]:=UnitConvert[quantity,units]
UnitForm::usage="like UnitConvert but for postfix";


(* ::Input::Initialization:: *)
(* Make it so you can always UnitForm 0 into any units *)
(*UnitConvert[zero_?(#==0&),targetunit_]^:=Quantity[0,targetunit]*)
(*UnitConvert[0.,targetunit_]^:=Quantity[0,targetunit]*)


Subscript[s_String, q]:=Quantity[s]


ClearAll@loadQuantities;
quantityAssoc[HoldPattern@symb]:=<|\[HBar]->Quantity["ReducedPlanckConstant"]|>[symb]
(* Makes loadQuantities idempotent, so loadQuantities[loadQuantities[\[HBar]]]==loadQuantities[\[HBar]] *)
loadQuantities[q_Quantity]:=q;
(* Define constants that can be loaded *)
loadQuantities[HoldPattern@\[HBar]]:=\[HBar]=Quantity["ReducedPlanckConstant"];
loadQuantities[HoldPattern[h]]:=h=Quantity["PlanckConstant"];
loadQuantities[HoldPattern@c]:=c=Quantity["SpeedOfLight"];
loadQuantities[HoldPattern@Subscript[q, e]]:=Subscript[q, e]=Quantity["ElectronCharge"];
loadQuantities[HoldPattern@Subscript[m, e]]:=Subscript[m, e]=Quantity["ElectronMass"];
loadQuantities[HoldPattern@Subscript[m, p]]:=Subscript[m, p]=Quantity["ProtonMass"];
loadQuantities[HoldPattern@Subscript[m, n]]:=Subscript[m, n]=Quantity["NeutronMass"];
loadQuantities[HoldPattern@Subscript[m, \[Mu]]]:=Subscript[m, \[Mu]]=Quantity["MuonMass"];
loadQuantities[HoldPattern@Subscript[m, \[Tau]]]:=Subscript[m, \[Tau]]=Quantity["TauMass"];
loadQuantities[HoldPattern@Subscript[\[Epsilon], 0]]:=Subscript[\[Epsilon], 0]=Quantity["VacuumPermittivity"];
loadQuantities[HoldPattern@Subscript[\[Mu], 0]]:=Subscript[\[Mu], 0]=Quantity["VacuumPermeability"];
loadQuantities[HoldPattern@Subscript[a, 0]]:=Subscript[a, 0]=Quantity["BohrRadius"];
loadQuantities[HoldPattern@G]:=G=Quantity["GravitationalConstant"];
loadQuantities[HoldPattern@Subscript[N, A]]:=Subscript[N, A]=Quantity["AvogadroConstant"];
loadQuantities[HoldPattern@Subscript[k, B]]:=Subscript[k, B]=Quantity["BoltzmannConstant"];
(* Allow list of quantities to be loaded  *)
SetAttributes[loadQuantities,Listable]
(*(* Handle other symbols not defined above, and return 0 *)
loadQuantities::unknownSymb="Unknown symbol `1`";
loadQuantities[symb_]:=(Message[loadQuantities::unknownSymb,symb];symb);*)
(* Return unknown symbols unchanged *)
loadQuantities[symb_]:=symb;
(* Load product, sum, etc of constants at once *)
loadQuantities[HoldPattern[f_[symbs__]]]:=f@@loadQuantities[{symbs}]
(* Allow list of quantities to be loaded without surrounding in brackets *)
loadQuantities[symbs__]:=loadQuantities[{symbs}]
(* With no arguments, load all quantities *)
(* todo figure out how to not have to hardcode the -5 (# of non-definition defs) *)
loadQuantities[]:=(Keys[DownValues[loadQuantities]]/.loadQuantities->List)[[;;-5,1]]//Flatten//ReleaseHold//loadQuantities


also[f_][x_]:=(f@x;x)


alsoPrint[f_:Identity]:=also[Print@*f]


saveDirectory[]:=Module[
	{dir=FileNameJoin@{NotebookDirectory[],"mathematica_figures"}},
	If[
		!DirectoryQ@dir,
		CreateDirectory[dir],
		dir
	]
]
save[fig_,name_String,format_String:"pdf",dpi_Integer:500]:=Export[FileNameJoin@{saveDirectory[],name<>"."<>format},fig,ImageResolution->dpi]
save[fig_,name_String,formats_List,dpi_Integer:500]:=save[fig,name,#,dpi]&/@formats
alsoSave[name_String,format_String:"pdf",dpi_Integer:500]:=also[save[#,name,format,dpi]&]
alsoSave[name_String,formats_List,dpi_Integer:500]:=also[save[#,name,formats,dpi]&]


alsoCopyOpts[opts___]:=also[CopyToClipboard@Rasterize[#,opts]&];
alsoCopy=alsoCopyOpts[]


tableHeaded[headers_][list_]:=TableForm[list,TableHeadings->headers]
tableHeadedRows[rows_][list_]:=TableForm[list,TableHeadings->{rows,None}]
tableHeadedCols[cols_][list_]:=TableForm[list,TableHeadings->{None,cols}]


(* https://mathematica.stackexchange.com/questions/54629/what-are-the-standard-colors-for-plots-in-mathematica-10 *)
ClearAll[defaultColorData]
defaultColorData=ColorData@Which[
	$VersionNumber>=14.2,"DefaultPlotColors",
	$VersionNumber>=10,97,
	True,1
];


(* ::Input::Initialization:: *)
ClearAll[plotStyle,PlotColors]
(* TODO: it might be better/possible to scan through the args & combine with any existing PlotStyle? *)
PlotColors/:f_[fns_,args___,PlotColors[colors_],args2___]:=With[{cols=plotStyle[colors,fns]},
f[fns,args,PlotStyle->cols,args2]
]
plotStyle[colors_,fns_]:=Module[{
cfun=Switch[colors,
_ColorDataFunction,colors,
_,ColorData[colors]
],
ctype,
n=Length@fns
},
If[!MatchQ[cfun,_ColorDataFunction],
Throw[Subscript["`` is not a known color data", sf]@colors,Module]
];
ctype=cfun[[2]];
Which[
ctype=="Gradients",cfun/@Subdivide[Subscript[cfun[[3]], seq],n-1],
ctype=="Indexed",cfun/@Range@n,
ctype=="Named",Throw@"TODO: Named",
ctype=="Physical",Throw@"TODO: Physical",
True,Throw@"Error"
]
]


(* Pride Flags! *)
(* How to add gradients: https://mathematica.stackexchange.com/questions/57885/is-it-possible-to-insert-new-colour-schemes-into-colordata/57893#57893 *)
(* Flag rgb colors: https://www.flagcolorcodes.com/flags/pride *)

ColorData[1];
(* Export this function so users can add gradients as needed *)
insertGradient[name_,gradColors_]:=If[
	!MemberQ[ColorData["Gradients"],name],
	(
		AppendTo[
			DataPaclets`ColorDataDump`colorSchemes,
			{{name,"",{}},{"Gradients"},1,{0,1},gradColors,""}
		];
		AppendTo[
			DataPaclets`ColorDataDump`colorSchemeNames,
			name
		];
	)
]
Module[{data,names,colors},
	data=Import["https://raw.githubusercontent.com/Annie-Schwartz/YouTilities/master/flags.tsv","TSV","Numeric"->False];
	names=#<>"Flag"&/@data[[;;,1]];
	colors=Map[RGBColor["#"<>#]&,data[[;;,2;;]],{2}];
	
	insertGradient@@#&/@Transpose@{names,colors};
]


(* ::Input::Initialization:: *)
EigvecsT[A_,neigs_:"all",\[CapitalDelta]_:Automatic]:=Transpose@Eigvecs[A,neigs,\[CapitalDelta]]
EigsysT[A_,neigs_:"all",\[CapitalDelta]_:Automatic]:=MapThread[#1@#2&,{{Identity,Transpose},Eigsys[A,neigs,\[CapitalDelta]]}]


(* Exponentiate with something other than Times (useful for matrix powers with Dot) *)
Subscript/:Power[Subscript[mat_,mp],n_]:=MatrixPower[mat,n]
Subscript/:Power[Subscript[mat_,Dot],n_]:=MatrixPower[mat,n]


ClearAll@eigenStuff
eigenStuff::zeroEigenvectors="Some zero-eigenvectors";
eigenStuff::unequal="#vals!=#vecs";
eigenStuff[matrix_,opts:OptionsPattern[{sys->Eigensystem,ai\[Lambda]->False,rref->False,normalize->False}]]:=Module[
	{
		ai\[Lambda]=OptionValue@ai\[Lambda],
		rref=OptionValue@rref,
		normalize=OptionValue@normalize,
		sys=OptionValue@sys,
		len=Length@matrix,
		vecs,vals
	},
	{vals,vecs}=sys[matrix];
	vecs=If[normalize,Normalize/@vecs,vecs];
	If[ContainsAny[vecs,{Table[0,len]}],
		Throw[Message[eigenStuff::zeroEigenvectors]]
	];
	AI\[Lambda]=matrix-# IdentityMatrix@len&/@vals//Simplify;
	If[Length/@{vals,vecs}/.List->Equal,
		Grid[
			Join[
				{{"\[Lambda]",If[ai\[Lambda],"A-I\[Lambda]",Nothing],If[rref,"RREF",Nothing],"Eigenvector"}},
				{
					vals,
					If[ai\[Lambda],MatrixForm/@AI\[Lambda],Nothing],
					If[rref,MatrixForm@*RowReduce/@AI\[Lambda],Nothing],
					MatrixForm/@vecs
				}\[Transpose]
			],
			Frame->All
		],
		Message[eigenStuff::unequal]
	]
]


(* ::Input::Initialization:: *)
CirclePlus[mat_?MatrixQ,hc]:=mat+mat\[ConjugateTranspose]
CirclePlus[val_,cc]:=val+val\[Conjugate]


(* ::Input::Initialization:: *)
LoadBra[]:=(
Bra[{labels__}]:=Ket[{labels}]\[Conjugate];
BraKet[{a__},{b__}]:=Bra[{a}]\[Conjugate] . Ket[{b}];
)


(* ::Input::Initialization:: *)
LoadArbitrarySpinMatricesJ[S_,type_:"n",chain_:1]:=If[Length@DownValues@LoadArbitrarySpinMatrices==0,
"Please make sure to load Melt before running LoadArbitrarySpinMatricesJ!",
(*{J0,Jx,Jy,Jz,Jp,Jm,\[ScriptCapitalJ]x,\[ScriptCapitalJ]y,\[ScriptCapitalJ]z,\[ScriptCapitalJ]p,\[ScriptCapitalJ]m}=Eat[{S0,Sx,Sy,Sz,Sp,Sm,\[ScriptCapitalS]x,\[ScriptCapitalS]y,\[ScriptCapitalS]z,\[ScriptCapitalS]p,\[ScriptCapitalS]m},LoadArbitrarySpinMatrices[S,type,chain]];*)
Block[{S0,Sx,Sy,Sz,Sp,Sm,\[ScriptCapitalS]x,\[ScriptCapitalS]y,\[ScriptCapitalS]z,\[ScriptCapitalS]p,\[ScriptCapitalS]m},
ClearAll[J0,Jx,Jy,Jz,Jp,Jm];
LoadArbitrarySpinMatrices[S,type,chain];
J0=S0;Jx=Sx;Jy=Sy;Jz=Sz;Jp=Sp;Jm=Sm;
If[chain===1,
"Matrices loaded: J0 (=1), Jx, Jy, Jz, Jp, Jm",
\[ScriptCapitalJ]0=\[ScriptCapitalS]0;\[ScriptCapitalJ]x=\[ScriptCapitalS]x;\[ScriptCapitalJ]y=\[ScriptCapitalS]y;\[ScriptCapitalJ]z=\[ScriptCapitalS]z;\[ScriptCapitalJ]p=\[ScriptCapitalS]p;\[ScriptCapitalJ]m=\[ScriptCapitalS]m;"Matrices loaded: \[ScriptCapitalJ]0 (=1), \[ScriptCapitalJ]x, \[ScriptCapitalJ]y, \[ScriptCapitalJ]z, \[ScriptCapitalJ]p, \[ScriptCapitalJ]m"
]
]
]


(* ::Input::Initialization:: *)
ClearAll[BlockDiagonalMatrixZ]
BlockDiagonalMatrixZ[mat_]:=Module[{FIXZERO},
BlockDiagonalMatrix[
#-FIXZERO IdentityMatrix@Length@#&/@
BlockDiagonalMatrix[mat+FIXZERO IdentityMatrix@Length@mat]["Blocks"]
]
]


(* ::Input::Initialization:: *)
ClearAll[Sectorize]
Sectorize[H_,syms_]:=Module[{\[DoubleStruckCapitalI]=IdentityMatrix@Length@H,bd=Transpose@*Eigenvectors,U,Hbd},
(*bd[o_]:=With[{\[Lambda]svs=Eigensystem@o},
Transpose@\[Lambda]svs[[2]][[Ordering[\[Lambda]svs[[1]],All,Greater]]]
];*)
U=bd@Last@syms;
Do[
U=U . bd[Inverse[U] . sym . U],
{sym,Rest@Reverse@syms}
];
(* BlockDiagonalMatrix really hates it if there is a 0 block. So, add 1 before using BDM, then subtract 1 from each block before putting it back together.
	And yes, just subtracting 1 from the full BDM makes it mad too.
 *)
Hbd=BlockDiagonalMatrix[#-IdentityMatrix@Length@#&/@BlockDiagonalMatrix[Simplify[Inverse[U] . H . U]+\[DoubleStruckCapitalI]]["Blocks"]];

]


(* ::Input::Initialization:: *)
ClearAll[BlockDiagonalizer]
BlockDiagonalizer[ops__]:=Module[{os=Reverse@{ops},U},
U=BlockDiagonalizer@First@os;
Do[
U=U . BlockDiagonalizer[Inverse[U] . os[[idx]] . U],
{idx,2,Length@os}
];
U
]
BlockDiagonalizer[op_]:=LocalizeAll[{},{},
{\[Lambda]s,vs}=Eigensystem@op;
Transpose@vs[[Ordering[\[Lambda]s,All,Greater]]]
]
(*BlockDiagonalizer[op_]:=LocalizeAll[{},{},
{\[Lambda]s,vs}=Eigensystem@op;
evals=Sort[DeleteDuplicates@\[Lambda]s,Greater];
Transpose@flat1@Table[
Normalize/@vs[[Flatten@Position[\[Lambda]s,\[Lambda]]]],
{\[Lambda],evals}
]
]*)


(* ::Input::Initialization:: *)
ClearAll[BlockEigvals]
BlockEigvals[U_]:=With[{Ui=Inverse@U},
Eigvals[Ui . # . U]&
]
(*BlockEigvals[mat_,U_]:=With[{Ui=Inverse@U},
Eigvals[Ui.mat.U]
]*)
(*BlockEigvals2[mat_,U_]:=With[{Ui=Inverse@U},
Eigvals[BlockDiagonalMatrix[Ui.mat.U]]
]*)


(* ::Input::Initialization:: *)
ClearAll[PrePrintMatrixForm]
PrePrintMatrixForm=If[MatrixQ@#&&!MatchQ[#,_BlockDiagonalMatrix],MatrixForm@#,#]&;


ClearAll[enumerate]
enumerate=MapIndexed[{#2[[1]],#1}&];


SparseReplaceAll[s_SparseArray,rule_]:=With[{
		elems=ReplaceAll[s["NonzeroValues"],rule],
		default=ReplaceAll[s["Background"],rule]
	},
	SparseArray[
		Automatic,
		s["Dimensions"],
		default,
		{1,{s["RowPointers"],s["ColumnIndices"]},elems}
	]
]


(* ::Input::Initialization:: *)
Subscript[l_List,seq]:=Sequence@@l


(* ::Input::Initialization:: *)
ClearAll[AdaptiveTable]
SetAttributes[AdaptiveTable,HoldAll]
AdaptiveTable[HoldPattern@f_,{x_,xmin_,xmax_,n_},maxRecursion_:6]:=Module[{g,if},
g[xx_?NumericQ]:=f/.x->xx;
if=Quiet@FunctionInterpolation[g[x],{x,xmin,xmax},InterpolationPoints->n,MaxRecursion->maxRecursion];
{Flatten[if["Grid"]],if["ValuesOnGrid"]}\[Transpose]
]


(* ::Input::Initialization:: *)
ClearAll[TableN]
SetAttributes[TableN,HoldAll];
TableN[expr_,lists__]:=Module[{vars,ls},
vars=Extract[Hold@lists,{All,1}];
ls=List@@Extract[Hold@lists,{All,2}];
If[!AllSameBy[ls,Length],Throw["All lists must be the same length!"]];
ReleaseHold@Table[
ReplaceAll[
Hold[expr],
s_Symbol/;MemberQ[vars,Unevaluated@s]:>With[{eval=Extract[ls,First@Position[vars,Unevaluated@s]][[idx]]},eval/;True]
],
{idx,Length@ls[[1]]}
]
]


(* ::Input::Initialization:: *)
ClearAll[Benchmark,BenchmarkOutput]
Benchmark[fns_List,ns_List,OptionsPattern[{InputFromN->Identity,Timer->RepeatedTiming,RefImpl->1,CorrectTest->None,NLimits-><||>}]]:=Module[{
inputFromN=OptionValue[InputFromN],
refImpl=OptionValue[RefImpl],
correctTest=OptionValue[CorrectTest],
timer=OptionValue[Timer],
nLimits=OptionValue[NLimits],
timings,
outputs,
wrong,
debugReturn
},
{timings,outputs}=Transpose[table[
With[{input=inputFromN@n},
Table[(*
Print[fns[[fnIdx]]];*)
If[n<=Lookup[nLimits,fnIdx,\[Infinity]],timer@fns[[fnIdx]]@input,{None,None}],
{fnIdx,Length@fns}
]
],
{n,ns}
],
{3,2,1}
];
wrong=If[correctTest=!=None,
ref=outputs[[refImpl]];
Position[
Table[
TableN[
rf==None||o==None||correctTest[rf,o],
{rf,ref},
{o,output}
],
{output,outputs}
],
Except[True],
{2},
Heads->False
],
{}
];
debugReturn=If[Length[wrong]!=0,
KeyValueMap[
Print@Subscript["Error! `` is wrong (`` times)", sf][fns[[#1]],Length@#2]&,
GroupBy[wrong,First]
];
Print["Use Benchmark[...][\"Errors\"] for more information"];
{wrong,outputs,refImpl},
{}
];
BenchmarkOutput[ns,fns,timings,Subscript[debugReturn, seq]]
]
(*Format[BenchmarkOutput[timings]]:="Benchmarking results"*)
BenchmarkOutput[ns_,fns_,timings_,___][]:=timings
BenchmarkOutput[ns_,fns_,timings_,wrong_:None,___]["Plot",args___]:=Module[{points={ns,#}\[Transpose]&/@timings},
(*Print@MatrixForm@points;*)
ListLogLogPlot[points,PlotLegends->fns,AxesLabel->{"n","time (seconds)"},PlotRange->All,Joined->True,args,PlotLabel->ToString@wrong]
]
BenchmarkOutput[ns_,fns_,___][Tabular,data_]:=Tabular[
ToTabular[
Join[{ns},data],
"Columns",
<|"ColumnKeys"->Join[{"n"},fns]|>
],
{"KeyColumns"->"n"},
ItemDisplayFunction->(#1/.None|0->""&)
]
BenchmarkOutput[ns_,fns_,timings_,___]["Summary"]:=BenchmarkOutput[ns,fns][Tabular,timings]
BenchmarkOutput[ns_,fns_,timings_,wrong_:None,outputs_:None,refImpl_:None]["Errors"]:=If[wrong===None,
"All implementations match!",
Module[{dropAll,fnsDrop,nsDrop,mask},
dropAll[expr_,seqs_]:=Fold[Drop,expr,Reverse@Sort@seqs];
mask=Normal[outputs SparseArray[Thread[wrong->1],{Length@fns,Length@ns}]];
fnsDrop=Position[mask,Table[0,Dimensions[mask][[2]]]];
mask=dropAll[mask,fnsDrop]\[Transpose];
nsDrop=Position[mask,Table[0,Dimensions[mask][[2]]]];
mask=dropAll[mask,nsDrop];
BenchmarkOutput[
dropAll[ns,nsDrop],
Join[{"Correct"},dropAll[fns,fnsDrop]]
][Tabular,
Join[{dropAll[outputs[[refImpl]],nsDrop]},mask\[Transpose]]
]
]
]


(* ::Input::Initialization:: *)
Subscript[s_String,sf][exprs__]:=StringForm[s,exprs]
Subscript[s_String,st]:=StringTemplate[s]


StringPrepend[rest_,pre_]:=pre<>ToString@rest
StringPrepend[pre_][rest_]:=StringPrepend[rest,pre]

StringAppend[rest_,app_]:=ToString@rest<>app
StringAppend[app_][rest_]:=StingAppend[rest,app]


(* ::Input::Initialization:: *)
ClearAll[Eat]
SetAttributes[Eat,HoldAll]
Eat[symbs_List,body_]:=Block[symbs,body;symbs]


(* ::Input::Initialization:: *)
ClearAll[WithWith]
SetAttributes[WithWith,HoldAll]
WithWith[list_List,body_]:=Fold[
ReplaceAll[{Hold[hinner_],Hold[hvar_]}->Hold@With[{hvar},hinner]]@*List,
Hold@body,
Reverse@First@Map[Hold,Hold@list,{2}]
]//ReleaseHold


(* ::Input::Initialization:: *)
ClearAll[cacheDirectory,cacheFile,cache,load,alsoCache,listCached]
cacheDirectory[source_:Automatic]:=FileNameJoin@{NotebookDirectory[],"mathematica_data",source/.Automatic->FileBaseName@NotebookFileName[]}
cacheFile[name_,source_:Automatic]:=Module[
	{file=FileNameJoin@{cacheDirectory[source],StringJoin[name,".mx"]}},
	If[
		!FileExistsQ@file,
		CreateFile[file],
		file
	]
]
cache[data_,name_,source_:Automatic]:=Export[cacheFile[name,source],data]
load[name_,source_:Automatic]:=Import[cacheFile[name,source]]
alsoCache[name_,source_:Automatic]:=also[cache[#,name,source]&]
listCached[source_:Automatic]:=FileBaseName/@FileNames[All,cacheDirectory[source]]


(* ::Input::Initialization:: *)
ClearAll[cachePlotData,alsoCachePlotData,loadPlotData]
SetAttributes[cachePlotData,HoldFirst]
cachePlotData[plot_,name_,source_:Automatic]:=Module[{vars,values},
vars=System`Utilities`SymbolList[Hold[plot],Hold,{"System`"}];
values=ReleaseHold@vars;
cache[{vars,values},"plot_data_"<>name,source];
plot
]
alsoCachePlotData[name_,source_:Automatic]:=Module[{f},
SetAttributes[f,HoldFirst];
f[plot_]:=cachePlotData[plot,name,source];
f
]
(* TODO maybe check if all symbols needed are available in the context this is being loaded into? *)
loadPlotData[name_,source_:Automatic]:=Module[{vv},
vv=load["plot_data_"<>name,source];
Table[
With[{v=ReleaseHold@vv[[1,i]]},Set[v,vv[[2,i]]]],
{i,Length@vv}
]
]


(* ::Input::Initialization:: *)
ClearAll[LocalizeAll];
SetAttributes[LocalizeAll,HoldAll];
LocalizeAll[code_]:=LocalizeAll[{},{},code]
LocalizeAll[extra_List,code_]:=LocalizeAll[extra,{},code]
LocalizeAll[extra_List,except_List,code_]:=Module[{expressions,locals},
expressions=List@@Map[Hold,Hold[code]/.CompoundExpression->List,{2}][[1]];
(*Echo[FullForm@expressions];
Echo[Hold@@Hold[except][[;;]]];*)
locals=Complement[
Join@@Join[
(* lhs=rhs *)
Cases[expressions,
Hold[Set[lhs_,rhs_]]:>Switch[Hold[lhs],
(* {lhs1,lhs2,...}=rhs *)
Hold[_List],Sequence@@Map[Hold,Hold[lhs],{2}][[1]],
(* lhs[[vars]]=lhs *)
Hold[_Part],Hold@@Map[Hold,Hold[lhs],{2}][[1,1]],
(* lhs=rhs *)
_,Hold[lhs]
]
],
(* lhs[vars]:=rhs  TODO: do I also need a Set (not Delayed) for this? *)
Cases[expressions,Hold[SetDelayed[lhs_[vars___],rhs_]]:>Hold@lhs],
(*(* TODO! lhs[[vars]]=lhs *)
Cases[expressions,Hold[Set[lhs_[[vars___]],rhs_]]:>Hold@lhs],*)
(* any extras :) *)
Hold/@extra
],
Hold@@except
]/.Hold[locals__]:>Hold[{locals}];
(*Echo@locals;*)
Module@@Hold[Evaluate[Unevaluated@@locals],code]
]



MatrixForm/@%["Blocks"]*)*)


(* ::Input:: *)
(*BlockDiagonalMatrix[{{*)
(* {1, 2, 3},*)
(* {2, 3, 4},*)
(* {3, 4, 5}*)
(*},{*)
(* {5, 6},*)
(* {6, 7}*)
(*}}]*)
(*BlockDiagonalMatrix[{{*)
(* {1, 2, 3},*)
(* {2, 3, 4},*)
(* {3, 4, 5}*)
(*},{*)
(* {5, 6},*)
(* {6, 7}*)
(*},{{0}}}]["Blocks"]*)


(* ::Input:: *)
(*fn[H,sym]:={U,ks,Hbd}*)


(* ::Input:: *)
(*LoadArbitrarySpinMatricesJ[j=1,"a"];*)
(*\[ScriptCapitalJ]0=J0\[CircleTimes]J0;*)
(*{\[ScriptCapitalJ]x,\[ScriptCapitalJ]y,\[ScriptCapitalJ]z}=Table[*)
(*kron@@Basis[2,idx]/.{1->op,0->J0},*)
(*{op,{Jx,Jy,Jz}},*)
(*{idx,2}*)
(*];*)
(*\[ScriptCapitalH][x_]:=-x Total@\[ScriptCapitalJ]z-(1-x)/(4j) \!\(\*SubsuperscriptBox[\(Total[\[ScriptCapitalJ]x]\), \(mp\), \(2\)]\)*)
(*\[CapitalPi]=Chop@MatrixExp[I \[Pi] (Jz-j J0)];*)
(*\[ScriptCapitalJ]2=\!\( *)
(*\*SubsuperscriptBox[\(Total[\[ScriptCapitalJ]x]\), \(mp\), \(2\)] + *)
(*\*SubsuperscriptBox[\(Total[\[ScriptCapitalJ]y]\), \(mp\), \(2\)] + *)
(*\*SubsuperscriptBox[\(Total[\[ScriptCapitalJ]z]\), \(mp\), \(2\)]\);*)
(*U=BlockDiagonalizer[\[ScriptCapitalJ]2,\[CapitalPi]\[CircleTimes]\[CapitalPi]];*)
(*Inverse[U] . \[ScriptCapitalH][x] . U//Simplify*)


(* ::Subsection::Closed:: *)
(*BlockDiagonalizer: Construct a unitary to block diagonalize according to some symmetry (i.e. operator)*)


(* ::Input::Initialization:: *)
ClearAll[BlockDiagonalizer]
BlockDiagonalizer[ops__]:=Module[{os=Reverse@{ops},U},
U=BlockDiagonalizer@First@os;
Do[
U=U . BlockDiagonalizer[Inverse[U] . os[[idx]] . U],
{idx,2,Length@os}
];
U
]
BlockDiagonalizer[op_]:=LocalizeAll[{},{},
{\[Lambda]s,vs}=Eigensystem@op;
Transpose@vs[[Ordering[\[Lambda]s,All,Greater]]]
]
(*BlockDiagonalizer[op_]:=LocalizeAll[{},{},
{\[Lambda]s,vs}=Eigensystem@op;
evals=Sort[DeleteDuplicates@\[Lambda]s,Greater];
Transpose@flat1@Table[
Normalize/@vs[[Flatten@Position[\[Lambda]s,\[Lambda]]]],
{\[Lambda],evals}
]
]*)


(* ::Subsubsection:: *)
(*Example Usage*)


(* ::Text:: *)
(*The following model of two coupled spins:*)


(* ::Input:: *)
(*<<C:\Users\annie\Documents\Rochester\Research\melt.m*)


(* ::Input:: *)
(*LoadArbitrarySpinMatricesJ[j=2,"a"];*)
(*\[ScriptCapitalJ]0=J0\[CircleTimes]J0;*)
(*{\[ScriptCapitalJ]x,\[ScriptCapitalJ]y,\[ScriptCapitalJ]z}=Table[*)
(*kron@@Basis[2,idx]/.{1->op,0->J0},*)
(*{op,{Jx,Jy,Jz}},*)
(*{idx,2}*)
(*];*)
(*\[ScriptCapitalH][x_]:=-x Total@\[ScriptCapitalJ]z-(1-x)/(4j) \!\(\*SubsuperscriptBox[\(Total[\[ScriptCapitalJ]x]\), \(mp\), \(2\)]\)*)


(* ::Text:: *)
(*conserves parity (\[CapitalPi]) and total spin \[ScriptCapitalJ]2:*)


(* ::Input:: *)
(*\[CapitalPi]=Chop@MatrixExp[I \[Pi] (Jz-j J0)];*)
(*\[ScriptCapitalJ]2=\!\( *)
(*\*SubsuperscriptBox[\(Total[\[ScriptCapitalJ]x]\), \(mp\), \(2\)] + *)
(*\*SubsuperscriptBox[\(Total[\[ScriptCapitalJ]y]\), \(mp\), \(2\)] + *)
(*\*SubsuperscriptBox[\(Total[\[ScriptCapitalJ]z]\), \(mp\), \(2\)]\)//Chop;*)
(*\[DoubleStruckCapitalC][\[ScriptCapitalH][x],\[CapitalPi]\[CircleTimes]\[CapitalPi]]//Simplify//MatrixForm*)
(*Map[Chop@*Simplify,\[DoubleStruckCapitalC][\[ScriptCapitalH][x],\[ScriptCapitalJ]2],{2}]//MatrixForm*)


(* ::Text:: *)
(*Thus, we can find a unitary matrix U that simultaneously (block) diagonalizes \[ScriptCapitalH] (or anything else that commutes with \[CapitalPi] and \[ScriptCapitalJ]2) into blocks of definite parity and total spin:*)


(* ::Input:: *)
(*fn[H,sym]:={U,ks,Hbd}*)


(* ::Input:: *)
(*U=BlockDiagonalizer[\[ScriptCapitalJ]2,\[CapitalPi]\[CircleTimes]\[CapitalPi]];*)
(*Ui=Inverse@U;*)
(*(*Dimensions@U*)
(*Ui.(\[CapitalPi]\[CircleTimes]\[CapitalPi]).U//Chop//MatrixForm*)
(*Ui.\[ScriptCapitalH][x].U//Simplify//Chop//MatrixForm*)
(*Ui.\[ScriptCapitalH][1].U//Chop//MatrixForm*)
(*Ui.\[ScriptCapitalH][0].U//Chop//MatrixForm*)*)


(* ::Input:: *)
(*tmp1=Ui . \[ScriptCapitalJ]2 . U//Diagonal;*)
(*tmp2=Ui . (\[CapitalPi]\[CircleTimes]\[CapitalPi]) . U//Diagonal;*)


(* ::Input:: *)
(*DeleteDuplicates@Transpose[{tmp1,tmp2}]*)


(* ::Input:: *)
(*$PrePrint=PrePrintMatrixForm;*)


(* ::Input:: *)
(*BlockDiagonalMatrix[\!\(\**)
(*TagBox[*)
(*RowBox[{"(", "", GridBox[{*)
(*{"3.", "5.", "4.", "0.", "0.", "0."},*)
(*{"2.", "1.", "7.", "0.", "0.", "0."},*)
(*{"6.", "8.", "9.", "0.", "0.", "0."},*)
(*{"0.", "0.", "0.", *)
(*RowBox[{"-", "1."}], "0.", "0."},*)
(*{"0.", "0.", "0.", "0.", "5.", *)
(*RowBox[{"-", "2."}]},*)
(*{"0.", "0.", "0.", "0.", *)
(*RowBox[{"-", "2."}], "0."}*)
(*},*)
(*GridBoxAlignment->{"Columns" -> {{Center}}, "Rows" -> {{Baseline}}},*)
(*GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.7]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}}], "", ")"}],*)
(*Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\)]*)


(* ::Input:: *)
(*tmp=Chop[Ui . \[ScriptCapitalH]2[0.5] . U];*)
(*BlockDiagonalMatrix@%*)


(* ::Input:: *)
(*BlockDiagonalMatrix[N@tmp]*)


(* ::Input:: *)
(*MatrixForm@tmp*)


(* ::Input:: *)
(*bdm=BlockDiagonalMatrix[Chop[Ui . \[ScriptCapitalH]2[0.5] . U//Simplify]]*)


(* ::Input:: *)
(*bdm*)


(* ::Input:: *)
(*bdm["Block"]*)


(* ::Text:: *)
(*Note that the order of symmetries is important! The above is first block diagonalized by total spin, the below first block diagonalizes by parity:*)


(* ::Input:: *)
(*U=BlockDiagonalizer[\[CapitalPi]\[CircleTimes]\[CapitalPi],\[ScriptCapitalJ]2];*)
(*Ui=Inverse@U;*)
(*Ui . \[ScriptCapitalH][x] . U//Simplify//MatrixForm*)
(*Ui . \[ScriptCapitalH][1] . U//MatrixForm*)


(* ::Subsection::Closed:: *)
(*BlockEigvals: Diagonalize a block diagonalizable matrix*)


(* ::Text:: *)
(*\:26a0\:fe0f Note that this will give incorrect eigenvalues if the matrix doesn't commute with each of the symmetry operators.*)


(* ::Input::Initialization:: *)
ClearAll[BlockEigvals]
BlockEigvals[U_]:=With[{Ui=Inverse@U},
Eigvals[Ui . # . U]&
]
(*BlockEigvals[mat_,U_]:=With[{Ui=Inverse@U},
Eigvals[Ui.mat.U]
]*)
(*BlockEigvals2[mat_,U_]:=With[{Ui=Inverse@U},
Eigvals[BlockDiagonalMatrix[Ui.mat.U]]
]*)


(* ::Input:: *)
(*LoadLMG[j=2^2];*)
(*Chop[Inverse[U[j]] . \[ScriptCapitalH][h] . U[j]]//EchoFunction@MatrixForm;*)
(*bd=BlockDiagonalMatrix[%]*)


(* ::Input:: *)
(*<<C:\Users\annie\Documents\Rochester\Research\melt.m*)
(*<<"C:\Users\annie\Documents\Rochester\Research\LMG\LMG Notebook.m"*)


(* ::Input:: *)
(*js=2^Range[10];*)
(*Do[LoadLMG[j];ParityBlockEigvals[j]=BlockEigvals[Quiet@BlockDiagonalizer[\[CapitalPi]]//EchoTiming],{j,js}];*)


(* ::Input:: *)
(*fns={Quiet@*Eigvals,Last@*Quiet@*LMGEigen,Quiet@*ParityBlockEigvals[j]};*)
(*fnNames={"Eigvals","LMGEigen[[-1]]","ParityBlockEigvals"};*)
(*ClearAll[j]*)
(*timings=Benchmark[fns,js,*)
(*j|->(LoadLMG@j;\[ScriptCapitalH][1.2])*)
(*]*)


(* ::Input:: *)
(*ListLogLogPlot[timings,PlotLegends->fnNames,AxesLabel->{"j","time (seconds)"},PlotRange->All,Joined->True]*)
(*timings[[;;,;;,2]]\[Transpose]//tableHeaded@{js,fnNames}*)


(* ::Input:: *)
(**)


(* ::Subsubsection:: *)
(*Example Usage:*)


(* ::Section::Closed:: *)
(*Miscellaneous*)


(* ::Subsection::Closed:: *)
(*PrePrintMatrixForm: Assign to $PrePrint to format matrices automatically *)


(* ::Input::Initialization:: *)
ClearAll[PrePrintMatrixForm]
PrePrintMatrixForm=If[MatrixQ@#&&!MatchQ[#,_BlockDiagonalMatrix],MatrixForm@#,#]&;


(* ::Subsection::Closed:: *)
(*Enumerate: Like enumerate in every other language*)


ClearAll[enumerate]
enumerate=MapIndexed[{#2[[1]],#1}&];


(* ::Subsection::Closed:: *)
(*SparseReplaceAll: Like ReplaceAll but works with SparseArrays*)


(* ::Text:: *)
(*https : // mathematica . stackexchange . com/a/154287*)


SparseReplaceAll[s_SparseArray,rule_]:=With[{
		elems=ReplaceAll[s["NonzeroValues"],rule],
		default=ReplaceAll[s["Background"],rule]
	},
	SparseArray[
		Automatic,
		s["Dimensions"],
		default,
		{1,{s["RowPointers"],s["ColumnIndices"]},elems}
	]
]


(* ::Subsubsection:: *)
(*Example Usage*)


(* ::Text:: *)
(*Say we have a sparse matrix with values Subscript[\[Mu], i] above and below the diagonal:*)


(* ::Input:: *)
(*A=SparseArray[*)
(*{*)
(*Band[{1,2}]->Array[Subscript[\[Mu], #]&,{3}],*)
(*Band[{2,1}]->Array[Subscript[\[Mu], #]&,{3}]*)
(*},*)
(*{4,4}*)
(*]*)
(*Eigenvalues[A]*)


(* ::Text:: *)
(*And we now have specific values of Subscript[\[Mu], i] we want to use:*)


(* ::Input:: *)
(*rules=Array[Subscript[\[Mu], #]->RandomReal[{-10,10}]&,3]*)


(* ::Text:: *)
(*The normal replacement doesn't work!*)


(* ::Input:: *)
(*A/.rules*)
(*ReplaceAll[A,rules] (* equivalent to the above *)*)
(*Eigenvalues[%]*)


(* ::Text:: *)
(*So we use SparseReplaceAll instead!*)


(* ::Input:: *)
(*SparseReplaceAll[A,rules]*)
(*Eigenvalues[%]*)


(* ::Subsection:: *)
(*fMap: Removed, see Comap*)


(* ::Subsection::Closed:: *)
(*Subscript[{list}, seq]: Convert a List to a Sequence*)


(* ::Input::Initialization:: *)
Subscript[l_List,seq]:=Sequence@@l


(* ::Subsubsection:: *)
(*Example Usage:*)


(* ::Input:: *)
(*f[Subscript[{1,2,3}, seq]]*)


(* ::Subsection::Closed:: *)
(*AdaptiveTable: like Table but with adaptive point sampling a la Plot*)


(* ::Input::Initialization:: *)
ClearAll[AdaptiveTable]
SetAttributes[AdaptiveTable,HoldAll]
AdaptiveTable[HoldPattern@f_,{x_,xmin_,xmax_,n_},maxRecursion_:6]:=Module[{g,if},
g[xx_?NumericQ]:=f/.x->xx;
if=Quiet@FunctionInterpolation[g[x],{x,xmin,xmax},InterpolationPoints->n,MaxRecursion->maxRecursion];
{Flatten[if["Grid"]],if["ValuesOnGrid"]}\[Transpose]
]


(* ::Input:: *)
(*t[l_]:={l,Range@Length@l}\[Transpose]*)


(* ::Input:: *)
(*myf=1/\[Pi] ArcTan[1000(x-1/2)];*)
(*dom={0,1};*)
(*as=AdaptiveTable[myf,Evaluate@{x,Subscript[dom, seq],30}]//EchoTiming;*)
(*(*asOld=AdaptiveTable2[myf,Evaluate@{x,Subscript[dom, seq],10},50];*)*)
(*s=Table[{x,myf},Evaluate@{x,Subscript[dom, seq],(dom[[2]]-dom[[1]])/Length@as}]//EchoTiming;*)
(*ListPlot[{as,s},Joined->True,Mesh->None,PlotStyle->Automatic,PlotLegends->{"Adaptively sampled points","Uniformly spaced points"},PlotLabel->Subscript["See how left plot is smoother at curves (`` points)", sf]@Length@as,ImageSize->Full,PlotLayout->"Row",PlotRange->All]*)
(*ListPlot[t/@{as,s}[[;;,;;,1]],PlotLabel->"Comparison of sampled points",ImageSize->Large]*)


(* ::Input:: *)
(*FunctionInterpolation*)


(* ::Input:: *)
(*myf=Sin[1/x];*)
(*dom={0.01,1.5};*)
(*as=AdaptiveTable[myf,Evaluate@{x,Subscript[dom, seq],50}]//EchoTiming;*)
(*(*as=AdaptiveTable[myf,Evaluate@{x,Subscript[dom, seq],200},5];*)*)
(*s=Table[{x,myf},Evaluate@{x,Subscript[dom, seq],(dom[[2]]-dom[[1]])/Length@as}]//EchoTiming;*)
(*ListPlot[{as,s},Joined->True,Mesh->None,PlotStyle->Automatic,PlotLegends->{"Adaptively sampled points","Uniformly spaced points"},PlotLabel->Subscript["See how left plot is smoother at curves (`` points)", sf]@Length@as,ImageSize->Full,PlotLayout->"Row",PlotRange->All]*)
(*ListPlot[t/@{as,s}[[;;,;;,1]],PlotLabel->"Comparison of sampled points",ImageSize->Large]*)


(* ::Subsection::Closed:: *)
(*TableN: Table through multiple lists in lockstep*)


(* ::Input::Initialization:: *)
ClearAll[TableN]
SetAttributes[TableN,HoldAll];
TableN[expr_,lists__]:=Module[{vars,ls},
vars=Extract[Hold@lists,{All,1}];
ls=List@@Extract[Hold@lists,{All,2}];
If[!AllSameBy[ls,Length],Throw["All lists must be the same length!"]];
ReleaseHold@Table[
ReplaceAll[
Hold[expr],
s_Symbol/;MemberQ[vars,Unevaluated@s]:>With[{eval=Extract[ls,First@Position[vars,Unevaluated@s]][[idx]]},eval/;True]
],
{idx,Length@ls[[1]]}
]
]


(* ::Subsubsection:: *)
(*Example:*)


(* ::Text:: *)
(*Say we have some eigenvalues & states we want to iterate over together:*)


(* ::Input:: *)
(*{Es,\[Psi]s}=N@Eigensystem[\!\(\**)
(*TagBox[*)
(*RowBox[{"(", "", GridBox[{*)
(*{*)
(*RowBox[{"-", *)
(*FractionBox["17", "8"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*SqrtBox["7"], "16"]}], "0", "0", "0", "0", "0", "0"},*)
(*{"0", *)
(*RowBox[{"-", *)
(*FractionBox["59", "32"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*RowBox[{"3", " ", *)
(*SqrtBox[*)
(*FractionBox["7", "4"]]}], "16"]}], "0", "0", "0", "0", "0"},*)
(*{*)
(*RowBox[{"-", *)
(*FractionBox[*)
(*SqrtBox["7"], "16"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox["3", "2"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*RowBox[{"3", " ", *)
(*SqrtBox[*)
(*FractionBox["5", "2"]]}], "16"]}], "0", "0", "0", "0"},*)
(*{"0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*RowBox[{"3", " ", *)
(*SqrtBox["7"]}], "32"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox["35", "32"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox["5", "16"]}], "0", "0", "0"},*)
(*{"0", "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*RowBox[{"3", " ", *)
(*SqrtBox[*)
(*FractionBox["5", "2"]]}], "16"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox["5", "8"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*RowBox[{"3", " ", *)
(*SqrtBox[*)
(*FractionBox["5", "2"]]}], "16"]}], "0", "0"},*)
(*{"0", "0", "0", *)
(*RowBox[{"-", *)
(*FractionBox["5", "16"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox["3", "32"]}], "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*RowBox[{"3", " ", *)
(*SqrtBox["7"]}], "32"]}], "0"},*)
(*{"0", "0", "0", "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*RowBox[{"3", " ", *)
(*SqrtBox[*)
(*FractionBox["5", "2"]]}], "16"]}], "0", *)
(*FractionBox["1", "2"], "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*SqrtBox["7"], "16"]}]},*)
(*{"0", "0", "0", "0", "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*RowBox[{"3", " ", *)
(*SqrtBox[*)
(*FractionBox["7", "4"]]}], "16"]}], "0", *)
(*FractionBox["37", "32"], "0"},*)
(*{"0", "0", "0", "0", "0", "0", *)
(*RowBox[{"-", *)
(*FractionBox[*)
(*SqrtBox["7"], "16"]}], "0", *)
(*FractionBox["15", "8"]}*)
(*},*)
(*GridBoxAlignment->{"Columns" -> {{Center}}, "Rows" -> {{Baseline}}},*)
(*GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.7]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}}], "", ")"}],*)
(*Function[BoxForm`e$, MatrixForm[SparseArray[Automatic, {9, 9}, 0, {1, {{0, 2, 4, 7, 10, 13, 16, 19, 21, 23}, {{1}, {3}, {2}, {4}, {3}, {1}, {5}, {4}, {2}, {6}, {3}, {5}, {7}, {6}, {4}, {8}, {7}, {5}, {9}, {8}, {6}, {9}, {7}}}, {Rational[-17, 8], Rational[-1, 16] 7^Rational[1, 2], Rational[-59, 32], Rational[-3, 16] Rational[7, 4]^Rational[1, 2], Rational[-3, 2], Rational[-1, 16] 7^Rational[1, 2], Rational[-3, 16] Rational[5, 2]^Rational[1, 2], Rational[-35, 32], Rational[-3, 32] 7^Rational[1, 2], Rational[-5, 16], Rational[-3, 16] Rational[5, 2]^Rational[1, 2], Rational[-5, 8], Rational[-3, 16] Rational[5, 2]^Rational[1, 2], Rational[-3, 32], Rational[-5, 16], Rational[-3, 32] 7^Rational[1, 2], Rational[1, 2], Rational[-3, 16] Rational[5, 2]^Rational[1, 2], Rational[-1, 16] 7^Rational[1, 2], Rational[37, 32], Rational[-3, 16] Rational[7, 4]^Rational[1, 2], Rational[15, 8], Rational[-1, 16] 7^Rational[1, 2]}}]]]]\)];*)


(* ::Text:: *)
(*TableN give you multiple symbol names to work with:*)


(* ::Input:: *)
(*TableN[*)
(*{E,Mean@\[Psi]},*)
(*{E,Es},*)
(*{\[Psi],\[Psi]s}*)
(*]*)


(* ::Subsection:: *)
(*Benchmark: Compare time taken by different implementations of functions*)


(* ::Input::Initialization:: *)
ClearAll[Benchmark,BenchmarkOutput]
Benchmark[fns_List,ns_List,OptionsPattern[{InputFromN->Identity,Timer->RepeatedTiming,RefImpl->1,CorrectTest->None,NLimits-><||>}]]:=Module[{
inputFromN=OptionValue[InputFromN],
refImpl=OptionValue[RefImpl],
correctTest=OptionValue[CorrectTest],
timer=OptionValue[Timer],
nLimits=OptionValue[NLimits],
timings,
outputs,
wrong,
debugReturn
},
{timings,outputs}=Transpose[table[
With[{input=inputFromN@n},
Table[(*
Print[fns[[fnIdx]]];*)
If[n<=Lookup[nLimits,fnIdx,\[Infinity]],timer@fns[[fnIdx]]@input,{None,None}],
{fnIdx,Length@fns}
]
],
{n,ns}
],
{3,2,1}
];
wrong=If[correctTest=!=None,
ref=outputs[[refImpl]];
Position[
Table[
TableN[
rf==None||o==None||correctTest[rf,o],
{rf,ref},
{o,output}
],
{output,outputs}
],
Except[True],
{2},
Heads->False
],
{}
];
debugReturn=If[Length[wrong]!=0,
KeyValueMap[
Print@Subscript["Error! `` is wrong (`` times)", sf][fns[[#1]],Length@#2]&,
GroupBy[wrong,First]
];
Print["Use Benchmark[...][\"Errors\"] for more information"];
{wrong,outputs,refImpl},
{}
];
BenchmarkOutput[ns,fns,timings,Subscript[debugReturn, seq]]
]
(*Format[BenchmarkOutput[timings]]:="Benchmarking results"*)
BenchmarkOutput[ns_,fns_,timings_,___][]:=timings
BenchmarkOutput[ns_,fns_,timings_,wrong_:None,___]["Plot",args___]:=Module[{points={ns,#}\[Transpose]&/@timings},
(*Print@MatrixForm@points;*)
ListLogLogPlot[points,PlotLegends->fns,AxesLabel->{"n","time (seconds)"},PlotRange->All,Joined->True,args,PlotLabel->ToString@wrong]
]
BenchmarkOutput[ns_,fns_,___][Tabular,data_]:=Tabular[
ToTabular[
Join[{ns},data],
"Columns",
<|"ColumnKeys"->Join[{"n"},fns]|>
],
{"KeyColumns"->"n"},
ItemDisplayFunction->(#1/.None|0->""&)
]
BenchmarkOutput[ns_,fns_,timings_,___]["Summary"]:=BenchmarkOutput[ns,fns][Tabular,timings]
BenchmarkOutput[ns_,fns_,timings_,wrong_:None,outputs_:None,refImpl_:None]["Errors"]:=If[wrong===None,
"All implementations match!",
Module[{dropAll,fnsDrop,nsDrop,mask},
dropAll[expr_,seqs_]:=Fold[Drop,expr,Reverse@Sort@seqs];
mask=Normal[outputs SparseArray[Thread[wrong->1],{Length@fns,Length@ns}]];
fnsDrop=Position[mask,Table[0,Dimensions[mask][[2]]]];
mask=dropAll[mask,fnsDrop]\[Transpose];
nsDrop=Position[mask,Table[0,Dimensions[mask][[2]]]];
mask=dropAll[mask,nsDrop];
BenchmarkOutput[
dropAll[ns,nsDrop],
Join[{"Correct"},dropAll[fns,fnsDrop]]
][Tabular,
Join[{dropAll[outputs[[refImpl]],nsDrop]},mask\[Transpose]]
]
]
]


(* ::Subsubsection:: *)
(*Example Usage:*)


(* ::Text:: *)
(*Fibonacci sequence*)


(* ::Input:: *)
(*fibBuiltIn[n_]:=Fibonacci[n]*)
(*fibNest[n_]:=Nest[{#[[2]],#[[1]]+#[[2]]}&,{0,1},n][[1]](*+If[n==8,1,0]*)*)
(*fibLoop[n_]:=Block[{a=0,b=1,t},Do[{a,b}={b,a+b},n];b](*b]-If[n==4,2,0]*)*)
(*fns={fibBuiltIn,fibNest,fibLoop};*)
(*ns=2^Range[1,10];*)
(*bench=Benchmark[fns,ns,CorrectTest->Equal,Timer->AbsoluteTiming,NLimits-><|2->2^7|>];*)
(*ClearAll[ns,fns,timings,wrong,outputs,refImpl]*)
(*{ns,fns,timings,wrong,outputs,refImpl}=List@@bench;*)


(* ::Input:: *)
(*points={ns,#}\[Transpose]&/@timings*)
(*ListLogLogPlot[points,PlotLegends->fns,AxesLabel->{"n","time (seconds)"},PlotRange->All,Joined->True,PlotStyle->Directive[Thin,Dashed],Mesh->All(*,args*)]*)


(* ::Input:: *)
(*bench["Plot"]*)
(*bench["Summary"]*)
(*bench["Errors"]*)


(* ::Section::Closed:: *)
(*Strings*)


(* ::Subsection::Closed:: *)
(*"a string containing `` "Subscript[, sf/st]: StringForm/StringTemplate  *)


(* ::Input::Initialization:: *)
Subscript[s_String,sf][exprs__]:=StringForm[s,exprs]
Subscript[s_String,st]:=StringTemplate[s]


(* ::Subsubsection:: *)
(*Example Usage :*)


(* ::Text:: *)
(*StringForm displays as a string but keeps the StringForm head*)


(* ::Input:: *)
(*Subscript["Hello `` (``)", sf]["World",42]*)
(*%//InputForm*)


(* ::Text:: *)
(*StringTemplate evaluates to a string*)


(* ::Input:: *)
(*Subscript["Hello `` (``)", st]["World",42]*)
(*%//FullForm*)


(* ::Subsection::Closed:: *)
(*StringPrepend/StringAppend: Like Prepend/Append, but for Strings. *)


StringPrepend[rest_,pre_]:=pre<>ToString@rest
StringPrepend[pre_][rest_]:=StringPrepend[rest,pre]

StringAppend[rest_,app_]:=ToString@rest<>app
StringAppend[app_][rest_]:=StingAppend[rest,app]


(* ::Input:: *)
(**)


(* ::Section::Closed:: *)
(*Scoping*)


(* ::Subsection::Closed:: *)
(*Eat: Return symbols by name rather than leaking to global scope*)


(* ::Input::Initialization:: *)
ClearAll[Eat]
SetAttributes[Eat,HoldAll]
Eat[symbs_List,body_]:=Block[symbs,body;symbs]


(* ::Input:: *)
(*leak[val_]:=CoolVariable=val*)


(* ::Input:: *)
(*(* This sets CoolVariable in the global scope, so it is 5 after the function *)*)
(*leak[5];*)
(*CoolVariable*)
(*ClearAll[CoolVariable]*)


(* ::Input:: *)
(*(* Eat the function, so it doesn't assign to the global CoolVariable *)*)
(*Eat[{CoolVariable},leak["yummy"]][[1]]*)
(*CoolVariable*)
(*ClearAll[Dinner,CoolVariable]*)


(* ::Subsection::Closed:: *)
(*WithWith: If you've ever wanted to nest With's, this does that nicer :)*)


(* ::Text:: *)
(*Note that this is not needed as of Mathematica 14.2 (?), as With can now take multiple variable specification lists that depend on previous variables.*)


(* ::Input::Initialization:: *)
ClearAll[WithWith]
SetAttributes[WithWith,HoldAll]
WithWith[list_List,body_]:=Fold[
ReplaceAll[{Hold[hinner_],Hold[hvar_]}->Hold@With[{hvar},hinner]]@*List,
Hold@body,
Reverse@First@Map[Hold,Hold@list,{2}]
]//ReleaseHold


(* ::Subsubsection:: *)
(*Example Usage*)


(* ::Input:: *)
(*WithWith[{a=3,b=a+1,c2=a^2+b^2,c=Sqrt[c2]},StringForm["Pythagorean theorem: \!\(\*SuperscriptBox[\(``\), \(2\)]\)+\!\(\*SuperscriptBox[\(``\), \(2\)]\)=\!\(\*SuperscriptBox[\(``\), \(2\)]\)",a,b,c]]*)


(* ::Text:: *)
(*equivalent to*)


(* ::Input:: *)
(*With[{a=3},*)
(*With[{b=a+1},*)
(*With[{c2=a^2+b^2},*)
(*With[{c=Sqrt[c2]},*)
(*StringForm["Pythagorean theorem: \!\(\*SuperscriptBox[\(``\), \(2\)]\)+\!\(\*SuperscriptBox[\(``\), \(2\)]\)=\!\(\*SuperscriptBox[\(``\), \(2\)]\)",a,b,c]*)
(*]*)
(*]*)
(*]*)
(*]*)


(* ::Section::Closed:: *)
(*Data Saving*)


(* ::Subsection:: *)
(*cache, alsoCache, load, listCached: Save data to . mx files, then retrieve it*)


(* ::Input::Initialization:: *)
ClearAll[cacheDirectory,cacheFile,cache,load,alsoCache,listCached]
cacheDirectory[source_:Automatic]:=FileNameJoin@{NotebookDirectory[],"mathematica_data",source/.Automatic->FileBaseName@NotebookFileName[]}
cacheFile[name_,source_:Automatic]:=Module[
	{file=FileNameJoin@{cacheDirectory[source],StringJoin[name,".mx"]}},
	If[
		!FileExistsQ@file,
		CreateFile[file],
		file
	]
]
cache[data_,name_,source_:Automatic]:=Export[cacheFile[name,source],data]
load[name_,source_:Automatic]:=Import[cacheFile[name,source]]
alsoCache[name_,source_:Automatic]:=also[cache[#,name,source]&]
listCached[source_:Automatic]:=FileBaseName/@FileNames[All,cacheDirectory[source]]


(* ::Subsubsection:: *)
(*Example:*)


(* ::Input:: *)
(*RandomWord["KnownWords",20]//alsoCache["my_words"];*)


(* ::Input:: *)
(*listCached[]*)


(* ::Input:: *)
(*load["my_words"]*)


(* ::Input:: *)
(*load["words_also"]*)


(* ::Subsection:: *)
(*cachePlot: Save all required information for a call to ListPlot, ListDensityPlot, Plot etc*)


(* ::Input::Initialization:: *)
ClearAll[cachePlotData,alsoCachePlotData,loadPlotData]
SetAttributes[cachePlotData,HoldFirst]
cachePlotData[plot_,name_,source_:Automatic]:=Module[{vars,values},
vars=System`Utilities`SymbolList[Hold[plot],Hold,{"System`"}];
values=ReleaseHold@vars;
cache[{vars,values},"plot_data_"<>name,source];
plot
]
alsoCachePlotData[name_,source_:Automatic]:=Module[{f},
SetAttributes[f,HoldFirst];
f[plot_]:=cachePlotData[plot,name,source];
f
]
(* TODO maybe check if all symbols needed are available in the context this is being loaded into? *)
loadPlotData[name_,source_:Automatic]:=Module[{vv},
vv=load["plot_data_"<>name,source];
Table[
With[{v=ReleaseHold@vv[[1,i]]},Set[v,vv[[2,i]]]],
{i,Length@vv}
]
]


(* ::Subsubsection::Closed:: *)
(*the problem:*)


(* ::Text:: *)
(*do some calculations that take a while (pretend the matrix is bigger & it's more code than just one cell)*)


(* ::Input:: *)
(*A=RandomVariate@GaussianOrthogonalMatrixDistribution[4000];*)
(*Es=Sort@Eigenvalues@A//EchoTiming;*)
(*diffs=Differences@Es;*)
(*xrange={0,5Quartiles[diffs][[-1]]};*)


(* ::Input:: *)
(*Histogram[diffs,PlotRange->{xrange,Full}]//EchoTiming*)


(* ::Text:: *)
(*but now if the kernel is done, all of the relevant data (including styling things like xrange) is lost, and we obviously can't change the plot styling:*)


(* ::Input:: *)
(*ClearAll[A,Es,diffs]*)


(* ::Input:: *)
(*Histogram[diffs,PlotRange->{{0,.2},All},ColorFunction->Hue]*)


(* ::Subsubsection:: *)
(*solved, using cachePlotData:*)


(* ::Text:: *)
(*do some calculations that take a while (pretend the matrix is bigger & it's more code than just one cell)*)


(* ::Input:: *)
(*A=RandomVariate@GaussianOrthogonalMatrixDistribution[4096];*)
(*Es=Sort@Eigenvalues@A//EchoTiming;*)
(*diffs=Differences@Es;*)
(*xrange={0,5Quartiles[diffs][[-1]]};*)


(* ::Input:: *)
(*Histogram[diffs,PlotRange->{xrange,Full}]//alsoCachePlotData["documentation"]//EchoTiming*)


(* ::Text:: *)
(*but now if the kernel is done, all of the relevant data is lost, and we obviously can't change the plot styling*)
(*so we just have to load the data!*)


(* ::Input:: *)
(*ClearAll[A,Es,diffs,xrange]*)


(* ::Input:: *)
(*listCached[]*)


(* ::Input:: *)
(*loadPlotData["documentation"];*)


(* ::Input:: *)
(*Histogram[diffs,PlotRange->{xrange,All},ColorFunction->Hue]*)


(* ::Section::Closed:: *)
(*WIP*)


(* ::Subsection::Closed:: *)
(*LocalizeAll: Kinda like inverted module?*)


(* ::Text:: *)
(*The idea is to make a scoping function that makes Mathematica behave more like a reasonable language; i.e. rather than having to specify the name of each variable twice (once for the usage and again in the list of local variables), just assume that all variables that appear on the left side of an '=' are local (maybe with a list of exceptions as the first argument?) so each only has to be specified where it is defined.*)
(**)
(*Note that this is still in the WIP section, but it does *largely* work. There are just a few edge cases it breaks for (notably, setting values using indexing doesn't work, i.e. list[[index]]=value). Other than that, it does what it should, and so I still use it :)*)


(* ::Input::Initialization:: *)
ClearAll[LocalizeAll];
SetAttributes[LocalizeAll,HoldAll];
LocalizeAll[code_]:=LocalizeAll[{},{},code]
LocalizeAll[extra_List,code_]:=LocalizeAll[extra,{},code]
LocalizeAll[extra_List,except_List,code_]:=Module[{expressions,locals},
expressions=List@@Map[Hold,Hold[code]/.CompoundExpression->List,{2}][[1]];
(*Echo[FullForm@expressions];
Echo[Hold@@Hold[except][[;;]]];*)
locals=Complement[
Join@@Join[
(* lhs=rhs *)
Cases[expressions,
Hold[Set[lhs_,rhs_]]:>Switch[Hold[lhs],
(* {lhs1,lhs2,...}=rhs *)
Hold[_List],Sequence@@Map[Hold,Hold[lhs],{2}][[1]],
(* lhs[[vars]]=lhs *)
Hold[_Part],Hold@@Map[Hold,Hold[lhs],{2}][[1,1]],
(* lhs=rhs *)
_,Hold[lhs]
]
],
(* lhs[vars]:=rhs  TODO: do I also need a Set (not Delayed) for this? *)
Cases[expressions,Hold[SetDelayed[lhs_[vars___],rhs_]]:>Hold@lhs],
(*(* TODO! lhs[[vars]]=lhs *)
Cases[expressions,Hold[Set[lhs_[[vars___]],rhs_]]:>Hold@lhs],*)
(* any extras :) *)
Hold/@extra
],
Hold@@except
]/.Hold[locals__]:>Hold[{locals}];
(*Echo@locals;*)
Module@@Hold[Evaluate[Unevaluated@@locals],code]
]


(* ::Input:: *)
(*Hold[list[[idx]]]*)
(*(*Hold[{l1,l2,l3}]*)*)
(*Hold@@Map[Hold,%,{2}]*)
(*%[[1,1]]*)


(* ::Input:: *)
(*list={111,222};*)
(*LocalizeAll[{},{list},*)
(*list[[3]]=333;*)
(*AppendTo[list,555]*)
(*]*)
(*list*)


(* ::Subsubsection::Closed:: *)
(*Example*)


(* ::Input:: *)
(*c="C already has a value";*)
(*a={1,2};*)
(*list={111,222};*)
(*ClearAll[e,b]*)
(*SetAttributes[hiddenSet,HoldFirst]*)
(*hiddenSet[v_Symbol]:=v=E*)
(*returned=LocalizeAll[*)
(*{e(* any extra variables to localize, incase they were set indirectly *)},*)
(*{b,(* any variables to not localize, incase you want to define some in the gobal scope *)},*)
(*a=5+1;*)
(*hiddenSet[e];*)
(*(*list[[3]]=333;*)*)
(*Print[e," ",c," ",d];*)
(*{c,d}={1,2};*)
(*Print[e," ",c," ",d];*)
(*Print["a=",a];*)
(*{Mean,Test};*)
(*fn[var_]:=var/2;*)
(*b=fn[a]+1;*)
(*a-b*)
(*];*)
(*Print[*)
(*"returned: should be 2, is: ",returned,*)
(*"\na: should be {1,2}, is: ",a,*)
(*"\nDownValues@fn: should be {}, is: ",DownValues@fn,*)
(*"\ne: should be e, is: ",N@e,*)
(*"\nc: should be \"C already has a value\", is: ",c,*)
(*"\nd: should be d, is: ",d,*)
(*"\nb: should be 4, is: ",b,*)
(*"\nlist: should be {111,222,333}, is: ",list*)
(*]*)


(* ::Subsubsection:: *)
(*Example: if LocalizeAll was implemented using LocalizeAll instead of Module*)


(* ::Input:: *)
(*SetAttributes[localizeAllOuroboros,HoldAll]*)
(*localizeAllOuroboros[extra_List,except_List,code_]:=LocalizeAll[{},{},*)
(*expressions=List@@Map[Hold,Hold[code]/.CompoundExpression->List,{2}][[1]];*)
(*locals=Complement[*)
(*Join@@Join[*)
(*Cases[expressions,Hold[Set[lhs_,rhs_]]:>Switch[lhs,*)
(*_List,Sequence@@Map[Hold,Hold[lhs],{2}][[1]],*)
(*_,Hold[lhs]*)
(*]],*)
(*Cases[expressions,Hold[SetDelayed[lhs_[vars___],rhs_]]:>Hold@lhs],*)
(*Hold/@extra*)
(*],*)
(*Hold@@except*)
(*]/.Hold[locals__]:>Hold[{locals}];*)
(*Module@@Hold[Evaluate[Unevaluated@@locals],code]*)
(*]*)
(*localizeAllOuroboros[{},{},a=2;a]*)
(*a*)
(*(* All of the local variables should be undefined still: *)*)
(*expressions*)
(*locals*)


(* ::Subsubsection:: *)
(*Example: timings, compared to Module*)


(* ::Input:: *)
(*ClearAll[b]*)
(*RepeatedTiming[*)
(*LocalizeAll[{e},{b},*)
(*a=5+1;*)
(*hiddenSet[e];*)
(*{c,d}={1,2};*)
(*(*Print[e," ",c," ",d];*)
(*Print["a=",a];*)*)
(*{Mean,Test};*)
(*fn[var_]:=var/2;*)
(*b=fn[a]+1;*)
(*a-b*)
(*]*)
(*]*)
(*ClearAll[b]*)
(*RepeatedTiming[*)
(*Module[{a,e,c,d,fb},*)
(*a=5+1;*)
(*hiddenSet[e];*)
(*{c,d}={1,2};*)
(*(*Print[e," ",c," ",d];*)
(*Print["a=",a];*)*)
(*{Mean,Test};*)
(*fn[var_]:=var/2;*)
(*b=fn[a]+1;*)
(*a-b*)
(*]*)
(*]*)


(* ::Subsection::Closed:: *)
(*map: Map but with a progress indicator*)


(* ::Input:: *)
(*?Map*)


(* ::Input:: *)
(*map[f_,expr_]:=table[f[mapIter],{mapIter,List@@expr}]*)


(* ::Input:: *)
(*<<C:\Users\annie\Documents\Rochester\Research\melt.m*)


(* ::Input:: *)
(*Map[(Pause[.2];#^2)&,Range@5]*)
(*map[(Pause[.2];#^2)&,Range@5]*)



